databases:
  - name: riichi-calculator-db
    plan: free
    databaseName: riichi_calculator_db
    user: riichi_calculator_db_user

services:
  - type: web
    plan: free
    name: riichi_calculator
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:riichi_calculator -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: riichi-calculator-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
